#!/bin/sh

set -eu

sudo apt install -y dbus-x11 libfuse2 jq

APPDIR="$HOME/.local/opt/cursor"
APPIMAGE_URL=$(curl -sL https://www.cursor.com/api/download\?platform\=linux-x64\&releaseTrack\=stable | jq -r '.downloadUrl')
UPDATE_SCRIPT="$HOME/.local/bin/update-cursor"

dbus-launch --sh-syntax > /dev/null 2>&1 || true

mkdir -p "$APPDIR"
wget -O "$APPDIR/cursor.AppImage" "$APPIMAGE_URL"
chmod +x "$APPDIR/cursor.AppImage"
cp "cursor.png" "$APPDIR"
ln -sf "$APPDIR/cursor.AppImage" "$HOME/.local/bin/cursor"

mkdir -p "$HOME/.local/share/applications"
cat > "$HOME/.local/share/applications/cursor.desktop" << EOF
[Desktop Entry]
Type=Application
Name=Cursor
Exec=$APPDIR/cursor.AppImage --no-sandbox
Icon=$APPDIR/cursor.png
EOF

cat > "$UPDATE_SCRIPT" << 'EOF'
#!/bin/sh

APPDIR="$HOME/.local/opt/cursor"
APPIMAGE_URL=$(curl -sL https://www.cursor.com/api/download\?platform\=linux-x64\&releaseTrack\=stable | jq -r '.downloadUrl')

wget -O $APPDIR/cursor.AppImage $APPIMAGE_URL
chmod +x $APPDIR/cursor.AppImage
EOF

chmod +x "$UPDATE_SCRIPT"

mkdir -p "$HOME/.config/systemd/user"
cat > "$HOME/.config/systemd/user/update-cursor.service" << EOF
[Unit]
Description=Update Cursor

[Service]
ExecStart=$UPDATE_SCRIPT
Type=oneshot

[Install]
WantedBy=default.target
EOF

systemctl --user enable update-cursor.service
systemctl --user start update-cursor.service
